Feat/5,
Starbish/nest-study-eventory pull request #14
Opened 2024-12-07 18:41 UTC by Starbish

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-07 18:45 UTC, Starbish commented
한가지 질문하고 싶은 점이, Club 전용 Event 를 만들기 위해선, 기존의 Event 코드에 Club 관련 API를 사용하든, 그 반대가 되었든 결국 최소 서로 한 쪽을 주입(?)해야 하는 상황이 나오는 것 같은데요,

https://joorrr.tistory.com/24

위와 같은 식의 처리를 진행해야 하는 게 맞을까요? 혹여나 제가 너무 산으로 가는 것일까봐 확인받고 싶습니다.

감사합니다!

2024-12-08 03:33 UTC, worjs commented
모듈간 의존은 잘못하면 순환의존성 문제에 걸릴 수 있어서 저는 잘 안쓰긴 합니다.

오히려 그냥 EventRepository를 ClubModule에도 주입시키고 EventModule에도 주입시키고 그럴 수 있는데 그러면 또 EventRepository가 전역에서 2개가 생성되는거라(정확하진 않습니다) 좋진 않아요.

진짜 제대로 하면 Repsitory만 모아서 RepositoryModule로 만들고, 그걸 다른 모듈들에다가 import해서 꺼내쓰는 방법도 있긴 합니다.

근데 저는 그냥 귀찮아서 ClubRepository에서 getEventByID 이런거 대충 만들어 쓰긴 함 ,,,

자유입니다~

2024-12-08 03:39 UTC, worjs requested changes

2024-12-08 03:39 UTC, worjs commented on src/club/club.repository.ts
>    }
뭔가 아직 구현을 덜 하신 것 같네요?!

2024-12-08 03:39 UTC, worjs commented on src/club/club.repository.ts
>    }
원래는 구현 마무리 하면 드리는 코멘트인데 오늘 마감날이니까 바로 드릴게요.

---------
클럽을 탈퇴할 때는 고려해야 하는 사항들이 더 있습니다!

만약에 유저가 클럽에서 클럽 모임을 만들거나 참여했다면 어떻게 될까요?
클럽을 나온 유저인데 클럽 모임을 운영하거나 참여할 수 있게 됩니다.

이 부분을 잡아내서 어쩌라는건가요? 라고 질문하는게 출제의도(?) 였는데,

아무튼 요거는

- 클럽에서 나올 때 기준으로 이미 시작된 클럽 모임을 운영했거나, 참여했다면 그냥 둡니다.
- 클럽에서 나올 때 기준으로 아직 시작하지 않은 모임의 호스트라면, 해당 모임을 삭제합니다.
- 클럽에서 나올 때 기준으로 아직 시작하지 않은 모임에 참가 신청 상태라면, 모임에서 나옵니다.

이미 끝난 클럽 모임이라면, 클럽을 나왔더라도 나의 참여 기록으로 아카이빙 되어서 볼 수 있어야 하기 때문이고, 아직 시작하지 않았다면 다 정리해야하는 셈이라고 보시면 되겠습니다.

2024-12-08 03:39 UTC, worjs commented on src/club/club.repository.ts
>    }
요건 클럽 삭제 관련!

---
사실 클럽을 삭제할 때도 마찬가지로 고려해야 하는 상황들이 더 있습니다.

클럽 모임에 FK조건이 걸려있기 때문에 그냥 클럽을 지우려고 하면 클럽 모임들도 전부 지워야 합니다.
그러면 기존 유저들은 클럽이 없어졌다는 이유로 자기가 참여했던, 혹은 만들었던 모임들이 전부 없어지게 됩니다.

요거는 아카이빙이라는 개념을 도입해서 해결하기로 합니다.

- 클럽을 삭제할 때, 이미 시작된 모임들은 아카이빙됩니다.
- 클럽을 삭제할 때, 시작되지 않은 모임들은 삭제합니다.
- 아카이빙된 모임은 모임 참가자만 조회할 수 있습니다.
- 아카이빙된 모임의 리뷰는 모임 참가자만 조회할 수 있습니다.

조회 관련해서 더 수정해야 할 부분들이 있을거고,
현재 스키마로는 어려울 수 있기 때문에 스키마 변경도 고려해보시면 좋을듯!

2024-12-08 09:27 UTC, Starbish commented
아... 각 기능 단위마다 Repository 코드를 따로 분리하다보니 자연스럽게 Club 에서는 Event db에 바로 접근을 못 하는 줄 알았는데, 그게 아닌가 보네요...!! 제가 너무 어렵게 생각한 것 같습니다.

이제 좀 방향성이 보이네요 ㅎㅎㅎ 감사합니다 :)

2024-12-09 02:44 UTC, worjs requested changes

2024-12-09 02:44 UTC, worjs commented on src/club/club.service.ts
> +      else await this.clubRepository.leaveClubEvent(user.id, list[i].id);
아쉽지만 여기에는 2가지 문제가 있습니다.
1. 반복문 안에 쿼리 -> list 길이가 길 수록 쿼리 수가 늘어나고, 전체 응답시간을 크게 지연시킬 수 있습니다.
2. 트랜잭션 처리되지 않은 write 쿼리. -> 한 개라도 실패하거나 중단될 경우 DB 정합성이 깨질 수 있습니다.

이 경우에는위 부분을 repository.leaveClub 안으로 밀어넣고, 하나의 트랜잭션으로 묶어주시면 되겠습니다!

로직은 100% 맞아요!

2024-12-09 02:44 UTC, worjs commented on src/club/club.service.ts
> +      else await this.clubRepository.leaveClubEvent(user.id, list[i].id);
아 그리고 고민을 많이 하고 계신 것 같은데, 혹시 고민하시면서 더 좋은 방안이나 답답한 부분이 있으면 언제든지 이야기해주세요! 도와드릴게요.

2024-12-09 07:33 UTC, Starbish commented
최대한 말씀하신 부분을 개선해보려고 했습니다...ㅎㅎ.ㅎ....

뭔가 불필요한 작업을 과하게 한 것 같기도 하고요(?)

2024-12-09 08:00 UTC, worjs requested changes

2024-12-09 08:00 UTC, worjs commented on src/club/type/leave-club-data.type.ts
> +}
값은 UPPER_CASE로 이름 지어주시는게 좋을거같아요
저 순간 inner 클래스 뭐 그런건가 하고 헷갈렸어요ㅋㅋㅋ

2024-12-09 08:00 UTC, worjs commented on src/club/type/leave-club-data.type.ts
> +}
enum 이름은 PascalCase 맞습니당

2024-12-09 08:00 UTC, worjs commented on src/club/club.repository.ts
> +    });
얘도 반복문 안에 쿼리가 들어가 있어요.

`deleteMany`만 사용하면 위 작업은 총 3~5번의 쿼리로 처리가 가능합니다.

최대한 `deleteMany`를 활용해서 한방에 지울 수 있게 개선해주시면 됩니다.

2024-12-09 08:00 UTC, worjs commented on src/club/club.service.ts
> +      });
그나저나 코드 진짜 잘만드시네요
이렇게 관리하면 누구나 쉽게 이해할 수 있을거라 생각합니다

2024-12-09 08:00 UTC, worjs commented on src/club/club.repository.ts
> +    });
아 그리구 eventJoin도
내가 나가는 경우는 내 eventJoin만 지우면 되지만, 내가 호스트인 경우는 모든 eventJoin을 지워야 한다는 차이가 있습니다!

2024-12-09 08:10 UTC, Starbish commented on src/club/type/leave-club-data.type.ts
> +}
수정했습니다 :)

2024-12-09 08:10 UTC, Starbish commented on src/club/club.repository.ts
> +    });
아.. 반복문을 지양해야 한다고 말씀하셨던 게 그런 의미였군요,,,, 최대한 Many를 이용해보겠습니다 :)

2024-12-09 08:11 UTC, Starbish commented on src/club/club.service.ts
> +      });
과찬이십니다,,ㅎㅎㅎ 남은 것도 열심히 해보겠습니다 :)

2024-12-09 10:29 UTC, Starbish commented
수정사항 반영해 보았습니다 :)

결국 슬프게도 칭찬받은 예쁜(?) 코드는 불필요했네요... ㅋㅋㅋ

2024-12-09 12:12 UTC, worjs approved these changes
굿!

근데 사실 원래 코드로 구현하는게 성능은 더 좋았을겁니다ㅎㅎ

2024-12-09 12:17 UTC, merged