Feat/7 클럽장 관련 기능 전부 구현
Starbish/nest-study-eventory pull request #16
Opened 2024-12-10 10:04 UTC by Starbish

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
아마... 다 구현한 것 같습니다(?)

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-10 10:07 UTC, Starbish commented
disbandClub() API의 repo 레이어 기능을 구현할 때 한 가지 고민이 되었던 점이, API는 DELETE로 명시되어 있는데, 특정 조건에 따라 POST(update) 동작을 하는 경우를 포함해도 되는지입니다. 

특정 조건 상에서 기존의 클럽 전용 모임을 아카이브화 하려면, 구현에 따라 다르겠지만 is_archive 라는 필드 값을 바꿔주어야 하는데, 사소하긴 하지만 DELETE가 아닌 동작을 포함하게 되는 부분이 신경쓰이더라구요. 이 부분에 대해 조언 주시면 감사하겠습니다 :)

2024-12-10 14:07 UTC, worjs requested changes

2024-12-10 14:07 UTC, worjs commented on src/club/club.repository.ts
> +      });
네네 괜찮습니다. 클라이언트가 DELETE라는 API만 봤을때는 그냥 클럽을 삭제하는 동작을 요청한거고, 클라이언트는 그 이상 서버와 데이터베이스가 아카이브 모임이니 뭐니를 어떻게 관리하는지 전혀 알 필요가 없으니까요.

예를 들면 우리가 내부 구현을 soft delete로 관리하게 되면 DELETE임에도 Update를 사용하게 되죠. 하지만 클라이언트 입장에서는 그런 것을 전혀 모르고, 알 필요도 없게 구현만 하면 됩니다.

2024-12-10 14:07 UTC, worjs commented on src/club/club.repository.ts
> +      where: {
그냥 매개변수 이름을 clubJoinId 하면 될지도? ㅋㅋㅋ

2024-12-10 14:07 UTC, worjs commented on src/review/review.repository.ts
>        },
클럽모임의 리뷰 관련 처리가 빠져있네요

2024-12-10 14:07 UTC, worjs commented on src/review/review.service.ts
> +
여기도 클럽 관련 처리 필요!

2024-12-10 14:08 UTC, worjs commented
다른부분 코드도 봤는데 이 PR만 마무리하면 패스로 하겠습니다~ 화이팅!

2024-12-10 16:46 UTC, Starbish commented
으어억... 수정하였습니다... 항상 감사합니다..

2024-12-11 02:09 UTC, worjs approved these changes
고생하셨습니닷

2024-12-11 04:42 UTC, merged