Week2 #16 구현입니다.
Starbish/nest-study-eventory pull request #4
Opened 2024-11-10 16:23 UTC by Starbish

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
 [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-11 00:50 UTC, worjs requested changes
data -> DTO로의 포장은 static from 메소드를 활용하기로 했었던 것 같아서 그렇게 변경해주셨으면 좋겠습니다~~! repository에서 event 가져오는 거 리턴 형태도 EventData로 기존에 만들어놓은 타입 적용해주시면 될 것 같구요

2024-11-11 00:54 UTC, worjs commented
아 그리고 미리 브랜치별로 작업해두신거면, 다 올리셔도 됩니다!
제가 대충 변경하신 코드만 리뷰드릴수도 있고, 아니면 타겟 브랜치를 잘 조정하면 내가 고친 부분만 리뷰에서 보이게 할 수도 있구요
하나 머지 될때마다 rebase - forcepush 방식으로 나머지 브랜치들도 다 반영할 수 있습니다.

2024-11-11 06:46 UTC, Starbish commented
피드백 주신 부분들 보완해서 올렸습니다!

과제들을 다 한 상태가 아니라 작성하는대로 바로 PR 올리고 있습니다 :)

빨리 끝내보겠습니다!

2024-11-11 09:11 UTC, Starbish commented
#18, #19 모두 추가되었습니다!

2024-11-12 11:33 UTC, Starbish commented
https://github.com/Starbish/nest-study-eventory/pull/7

위 PR로 모두 통합했습니다 :)

2024-11-12 11:33 UTC, closed without merging