Week3
Starbish/nest-study-eventory pull request #7
Opened 2024-11-12 11:31 UTC by Starbish

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
- Week 2의 #16, #17, #18, #19
- Week 3의 #33, #34, #36 구현입니다!

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-12 15:31 UTC, worjs requested changes
코멘트 확인해주세요!

화이팅!

2024-11-12 15:31 UTC, worjs commented on src/event/event.repository.ts
> +  }
Repository 입장에서는 자기가 어디서 사용될지도 모른채로 서비스 어디서든지 사용될 수 있어야 합니다. 그래서 특정 HTTP 요청의 DTO를 알고 그걸로 포장해서 리턴하는 구조는 잘못되었다고 생각합니다. 얘도 EventData 타입으로 만들고 EventListDto.from은 서비스에서 치는게 좋을 것 같아요!

2024-11-12 15:31 UTC, worjs commented on src/event/event.repository.ts
> +  }
얘네들은 굳이 리턴 없어도 되지 않을까... 하는 생각

2024-11-12 15:31 UTC, worjs commented on src/event/event.repository.ts
> +  }
사실 Patch라는거는 Http에서 쓰는 개념이기도 하거든요. 마찬가지로 DB 로직을 다루는 레포지토리는 그쪽과는 분리가 되어 있어야 한다고 생각합니다. update라는 용어가 좀 더 DB쪽에 적합한 용어라고 생각해요

2024-11-12 15:31 UTC, worjs commented on src/event/event.repository.ts
> +  }
전자만 성공하고 후자가 실패하는 경우에는 어떻게 될까요?
둘 다 write류의 쿼리기 때문에 둘 중에 하나가 실패하면 DB 정합성이 깨지게 됩니다.

둘다성공/둘다실패 처리는
https://www.prisma.io/docs/orm/prisma-client/queries/transactions
요기 참고하시면 될듯!

2024-11-12 15:31 UTC, worjs commented on src/event/query/search-event.query.ts
> +  }
controller에도 잘 설명해두셔서 사실 상관은 없는데요, 굳이 이 조건이 필요한 이유가 있었을까요

2024-11-12 15:31 UTC, worjs commented on src/event/event.service.ts
> +      throw new NotFoundException('입력한 카테고리 ID가 존재하지 않습니다.');
저는 요거 굳이? 라는 생각이긴 해요.
다른 곳에서의 NotFound검증은 실제로 그 id가 없으면 이후 요청(DB 저장)을 수행할 수 없는 경우에 한해서 했거든요. 근데 이 경우는 해당 id가 실제로 존재하는 값이 아니면, 검색결과로 빈 배열을 리턴하면 되는거라 안하긴 합니다.

2024-11-12 15:31 UTC, worjs commented on src/event/event.service.ts
> +      throw new ConflictException('해당 유저가 이미 모임에 속해 있습니다.');
저는 굳이 말하자면 첫번째 코드 스타일이 더 읽기 쉬워서 좋아하긴 합니다
근데 그렇다고 아래쪽 두 코드가 읽기 어려운 정도는 아니어서 상관 없긴한데, 하나로 통일하면 좋겠다는 생각은 드네요!

2024-11-12 15:31 UTC, worjs commented on src/event/event.service.ts
> +    this.eventRepository.leftFromEvent(userId, eventId);
await 들어가야 합니다!
안그러면 db 응답 결과를 받지 않고 HTTP 응답을 보내버리거든요.
db 응답 결과 에러가 발생해도 클라이언트한테 성공했다고 응답하게 됩니다.

2024-11-12 15:31 UTC, worjs commented on src/event/event.service.ts
> +    let endTime = body.endTime !== undefined ? body.endTime : prevEvent.endTime;
저도 이게 가장 현명한 방법인 것 같아요!
근데 값이 변하는건 아니어서 const로 가셔도 됨요

2024-11-12 15:31 UTC, worjs commented on src/event/event.service.ts
> +      );
하나 더 있죠?

2024-11-12 15:31 UTC, worjs commented on src/event/payload/patch-event.payload.ts
> +  title?: string;
이게 사실 좀 답답한 이야기긴 한데, @IsOptional은 null과 undefined를 둘 다 통과시킵니다.
그래서 실제로 타입은 `title?: string | null` 이 됩니다.
patch에서 null과 undefined는 구분을 해줘야 합니다.

repository에서 update할 때 null을 넣어주면 null이라는 값으로 변경하겠다는 뜻이고, undefined로 들어가면 변경을 안하겠다는 뜻이거든요.

IsOptional이 그걸 구분해서 받아주지 않아서, 서비스 코드 내에서 null을 하나하나 제거를 하고 있습니다. 더 좋은 방법이 있으면 좋겠는데 일단은 ,,,, review 모듈 참고해서 수정해주시면 될 것 같아요

2024-11-12 15:31 UTC, worjs commented on src/event/payload/patch-event.payload.ts
> +  title?: string;
그리고 undefined 가능한 필드는 @ApiOptionalProperty 써줘야 docs에서도 optional 필드로 나타납니다.

2024-11-12 15:31 UTC, worjs commented on src/event/payload/patch-event.payload.ts
> +  })
`@IsInt`
쟤는 유리수도 포함이더라구요

2024-11-13 02:20 UTC, Starbish commented on src/event/event.repository.ts
> +  }
Service와 Repository의 역할구분에 대해 더 신경써보겠습니다 😄

2024-11-13 02:24 UTC, Starbish commented on src/event/event.repository.ts
> +  }
엇.. 혹시 leftFromEvent() 도 포함되는건가요? Promise<void> 자료형은 리턴이 없는 것과 동일한 기능이라고 생각했습니다,,

joinEvent()는 리턴 빼겠습니다 😄

2024-11-13 02:30 UTC, Starbish commented on src/event/event.repository.ts
> +  }
사실 review 예시코드에는 patchUpdateReview 등의 형태로 작성되어 있는걸 보고.. 의미상 크게 중복된다고 생각해서 뺀건데 repository 입장에서는 이상한 작명이 될 수 있겠단 생각을 못 했네요..

수정해보겠습니다 😄

2024-11-13 02:30 UTC, Starbish commented on src/event/event.repository.ts
> +  }
어잇쿠... 같은 실수를 반복했네요 ㅎㅎ,,,,

2024-11-13 03:04 UTC, Starbish commented on src/event/event.repository.ts
> +  }
const result = 부분을 말씀하시는 것 같아서 제외해보겠습니다 :)

2024-11-13 03:06 UTC, Starbish commented on src/event/event.repository.ts
> +  }
Repository가 Service와 종속적이지 않아야 한다는 점을 놓치고 있었던 것 같습니다. 함수 작명을 할 때도 비슷하게 짓다보니 서로 종속적인 관계라고 생각한 것 같습니다. 좋은 지적 감사드려요 👍

2024-11-13 03:17 UTC, Starbish commented on src/event/query/search-event.query.ts
> +  }
아... 지금 과제 spec을 다시 읽어보니 제가 잘못 이해했네요... 😄 

2개 이상의 파라미터를 받아와야 하는 것으로 잘못 이해했습니다 ㅎㅎ,,,,, 수정하겠습니다 😄

2024-11-13 03:38 UTC, Starbish commented on src/event/event.service.ts
> +      throw new NotFoundException('입력한 카테고리 ID가 존재하지 않습니다.');
제가 저 코드를 작성한 의도는 "실제로 존재하지 않는 카테고리 혹은 도시 ID" 를 가지고 요청을 보내는 것 자체가 의도되지 않은 동작일 가능성이 높고, 그래서 개발 상에서 도움이 될만한 메시지로 기능할 수 있지 않을까 하는 부분이었습니다.

예를 들면, 클라이언트가 실제로 ID를 정수 데이터를 직접 입력해서 요청을 보낼 리는 없고, 앱이나 웹 상에서 제공하는 UI를 통해 그 값을 설정하고 요청을 보낼 것이라고 생각하는데, 이런 맥락에서 보았을 때 존재하지 않는 ID로 요청을 보내는 게 정상적인 동작이라는 생각이 들지는 않았던 것 같습니다.

아직 협업 경험이 없는지라 제가 너무 발생할 가능성이 낮은 부분에 대해 고려하고 있는 것 같기도 합니다. 😄 

또, 말씀하신대로 DB에 존재하지 않아 처리를 할 수 없는 경우가 아닌, DB에 존재하지 않아도 동작할 수 있는(결과없음으로) 경우이므로 exception 으로 처리하는 건 확실히 부자연스러운 것 같습니다. 😅

이것도 수정해보겠습니다!

2024-11-13 03:44 UTC, Starbish commented on src/event/event.service.ts
> +      throw new ConflictException('해당 유저가 이미 모임에 속해 있습니다.');
통일하겠습니다 :)

2024-11-13 03:46 UTC, Starbish commented on src/event/event.service.ts
> +    this.eventRepository.leftFromEvent(userId, eventId);
헉.. 수정했습니다

2024-11-13 03:46 UTC, Starbish commented on src/event/event.service.ts
> +    let endTime = body.endTime !== undefined ? body.endTime : prevEvent.endTime;
수정했습니다!

2024-11-13 04:33 UTC, Starbish commented on src/event/payload/patch-event.payload.ts
> +  })
수정했습니다 :)

2024-11-14 09:16 UTC, Starbish commented on src/event/event.service.ts
> +      );
어이쿠...

2024-11-14 09:20 UTC, Starbish commented on src/event/payload/patch-event.payload.ts
> +  title?: string;
뭔가 요청받은 데이터 검증을 service 모듈에서 하기 싫어서... 구글링으로 다른 방법을 찾아보았습니다

항상 꼼꼼한 피드백 감사드려요 😄

2024-11-14 17:15 UTC, worjs approved these changes
고생하셨습니다.

코멘트 보시고 적당히 머지하시면 될듯!

2024-11-14 17:15 UTC, worjs commented on src/event/payload/patch-event.payload.ts
> +}
Wow
커스텀으로 하나 만드는거군요
이렇게 쉬운거 이놈자식들 왜 안만들어줬을까...
잘 작동한다면 아주 나이스 ....

2024-11-14 17:15 UTC, worjs commented on src/event/event.service.ts
> +      );
이것도 굳이? query에 들어가는 값들은 기본적으로 optional한게 더 자연스러운 것으로 알고 있습니다.
만약에 아무 값도 안고를 경우 전체를 리턴한다고 이해할 수 있을 것 같아요!

2024-11-27 06:56 UTC, merged